### ISSUE TITLE
New version in pip?

### ISSUE THREAD

**Issue by TeddJohnson** [bluszcz/django-sb-admin#3]
I see that you made some updates so that the url.patterns() warning message would go away (regarding django 1.10) but it doesn't look like it's been updated in pip. Do you know when you will be pushing that update?

Appreciate this project, made "prettifying" my django much easier!

**Comment by bluszcz** [comment]
Yes, there will be a new release on the days :)

**Comment by bluszcz** [comment]
Little delay, sorry.
